export const TERMS_VERSION = "2026-09-16";
export const SUPPORT_EMAIL = "hackathon-shipaton@aamirazeez.com";
const shell = (title: string, body: string) => `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — After You</title><style>body{max-width:48rem;margin:3rem auto;padding:0 1.2rem;font:18px/1.6 system-ui,sans-serif;color:#20332d;background:#faf8f0}a{color:#176953}h1,h2{line-height:1.2}nav{margin-top:3rem}</style><main><h1>${title}</h1>${body}<nav><a href="/privacy">Privacy</a> · <a href="/account-deletion">Account deletion</a> · <a href="/community-rules">Community rules</a></nav><p>After You · Aamir Azeez · <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></p></main></html>`;
const pages: Record<string, string> = {
  "/privacy": shell("After You Privacy Policy", `<p>Effective 16 September 2026.</p>
<h2>Playing and connecting</h2><p>Solo progress is stored on your device. Online play and purchases use a randomly generated player identity protected by a device credential and recovery code. We do not ask for a name, email, phone number or social-login account. Our game server stores hashes of the credentials. Keep your recovery information private; never email it.</p>
<p>Online rooms store membership, accepted game inputs, replay checkpoints, progress, timestamps and supported preset reactions. A replay is game-action data, not a camera or microphone recording. Room information is available to its two invited participants. It runs and verifies shared turns and helps prevent invalid or conflicting submissions.</p>
<h2>Optional photos and Photo transfer</h2><p>The camera opens only when you choose it. Keeping a photo on your device does not upload it. Share uploads a compressed photo for your room partner. We remove embedded camera metadata, including EXIF location fields, from the JPEG; the image itself can still reveal personal information.</p>
<p>A shared server photo is removed when its owner deletes it, its room/account is erased, or both intended players confirm a verified copy is saved on their devices. Older versions may not provide this confirmation. Version, ownership and delivery metadata remains with the room. Deletion cannot erase copies or screenshots already saved by someone else.</p>
<p>Photo transfer is voluntary temporary storage for your own identity. It may include private, unshared photos you choose to transfer; it does not share those photos with your partner. It keeps at most the newest 1,000 entries within a storage budget. Entries expire after 14 days, may be displaced by newer entries at the count limit, or are removed after confirmed durable restore. New transfers normally start once per 24 hours. Capacity can refuse additional uploads. It is not permanent backup and does not transfer solo progress or purchases.</p>
<h2>Purchases, alerts and providers</h2><p>The Play edition uses Google Play and RevenueCat for purchase validation, restoration and purchase reporting. RevenueCat receives your app player ID and purchase information. We do not receive payment-card numbers. Demo editions use RevenueCat Test Store instead of real payment.</p>
<p>Optional turn alerts use Google Firebase Cloud Messaging. App-installation identifiers, messaging tokens and account bindings deliver generic friend-turn alerts with room/turn routing identifiers, never photos or recovery credentials. Disable alerts in app or Android settings. Delivery is best effort.</p>
<p>Cloudflare operates the game API and database, including photo storage. RevenueCat and Google Play support purchases; Google/Firebase delivers alerts. These providers process the information needed for their services. Network infrastructure processes connection information such as IP addresses; the API uses a hashed IP key to limit unauthenticated abuse. The app does not contain ads, sell personal data, or collect contacts, microphone recordings, location or advertising identifiers for its features. App analytics/crash-reporting SDKs are not enabled; RevenueCat provides purchase reporting.</p>
<h2>Security and retention</h2><p>Connections use HTTPS. This protects data in transit but is not end-to-end photo encryption. Online access is authenticated, and device credentials use Android protected storage. No system can guarantee against all loss or unauthorized access.</p>
<p>Identities and shared game records have no routine expiry; invite expiry only limits joining. Photo retention follows the rules above. Notification registrations and queued alerts have bounded lifetimes and account recovery/deletion invalidates bindings. Device photos can survive normal restarts and updates; uninstalling, clearing storage or device failure can lose them.</p>
<p>Community-rule acceptance and your block list are retained until changed or your account deletion. Another player's block list may keep your former player ID until they remove the block or delete their account. Safety reports contain reason and room/photo-reference metadata, not an automatic copy of the image; they are kept up to 90 days for investigation. Reports made by others may retain references to a deleted identity during that period. Providers may retain transaction or security records required by law.</p>
<h2>Your choices and deletion</h2><p>Settings → Account &amp; recovery → Delete online identity removes your server identity, linked rooms and their recordings/photos for both participants, temporary photo transfers and alert registrations. Provider customer deletion is requested separately and may be processed asynchronously. The app clears local photo data and credentials after server confirmation and offers a retry if device cleanup fails. Solo progress remains. Remote deletion cannot erase copies on another or offline device and does not refund a purchase or erase Google Play transaction records.</p>
<p>A small deletion-completion record containing your player ID, a hash of the old device credential and retry metadata remains until the deleting device confirms durable local cleanup. It lets a lost deletion reply be checked and cannot restore account access. If the device never confirms, this limited record remains; contact us for help.</p>
<p>You can also <a href="/account-deletion">request deletion without reinstalling</a>. Contact <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a> for privacy questions, access or correction requests, including concerns about a child's information. We verify ownership of anonymous identities before acting and explain any legitimate retention or limits.</p>`),
  "/account-deletion": shell("Delete your After You account", `<p>You can request deletion without reinstalling After You. Email <a href="mailto:${SUPPORT_EMAIL}?subject=After%20You%20account%20deletion">${SUPPORT_EMAIL}</a> with the subject “After You account deletion”. Include your player ID if you have it. <strong>Do not email a recovery code, device credential, photo or payment-card details.</strong> We will explain how to verify that the anonymous identity is yours. A player ID alone is not proof of ownership.</p>
<p>If the app is installed, use Settings → Account &amp; recovery → Delete online identity → Delete identity and shared rooms.</p><p>Deletion removes your online identity, shared rooms and their server recordings/replays/photos for both players, temporary photo transfers and alert registrations. It requests removal of your RevenueCat customer information. This cannot be undone using the old recovery code. It does not refund a content purchase or erase Google Play's transaction records.</p>
<p>On the deleting device, the app clears local photo data and credentials after confirmation and offers retry if cleanup fails. Solo progress remains. We cannot remotely erase another person's downloaded photos, screenshots or local replays, or data on an offline device. Limited safety reports and legally required provider records may remain as described in the <a href="/privacy">Privacy Policy</a>.</p>
<p>We will respond with verification steps and the expected completion time. If you have lost all proof of ownership, contact us so we can explain what is possible without risking another player's account.</p>`),
  "/community-rules": shell("After You Community Rules", `<p>Version ${TERMS_VERSION}. After You connects two invited players. You must accept these rules before uploading shared photos.</p>
<ul><li>Share only images you have permission to share and want the invited player to receive.</li><li>No sexual content, child exploitation, threats, harassment, hateful content, illegal content, or disclosure of another person's private information without permission.</li><li>Do not misuse reporting, invitations or account recovery to harm another person.</li></ul>
<p>Use Report in the app to submit a fixed reason and the room/photo reference for review. Reports do not automatically include a copy of your image. We may need you to provide evidence voluntarily if the server's photo has already been removed. Use Block to stop further room interaction and photo delivery with that identity; copies already saved on devices cannot be recalled. You can also contact <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p><p>We may remove content or restrict access when we find a violation. There is no public photo feed or free-text chat. Do not share an invitation with someone you do not want to play with.</p>`)
};

export function publicPolicy(request: Request): Response | null {
  const page = pages[new URL(request.url).pathname]; if (!page) return null;
  if (!["GET", "HEAD"].includes(request.method)) return new Response(null, { status: 405, headers: { Allow: "GET, HEAD" } });
  return new Response(request.method === "HEAD" ? null : page, { headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "public, max-age=300", "X-Content-Type-Options": "nosniff", "Referrer-Policy": "no-referrer", "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'" } });
}
