extends "res://tests/test_relay_room_coordinator.gd"
## Unchanged reads retain exact durable state. Receipts and auth are real writes.

func _run() -> void:
	for name: String in ["relay-a", "relay-b", "garden-a", "garden-b", "initial-checkpoint", "relay-checkpoint", "final-checkpoint"]:
		fixtures[name] = JSON.parse_string(FileAccess.get_file_as_string("res://tests/fixtures/v2/" + name + ".json"))
	await _identical_reads()
	await _pending_receipt()
	await _auth_and_validation()
	print("Room unchanged refresh: %d checks, %d failures" % [checks, failures])
	quit(1 if failures else 0)

func _identical_reads() -> void:
	var boundary := Boundary.new()
	var coordinator = await _open(boundary)
	var room: Dictionary = coordinator.snapshot()
	var state_hash := Canonical.digest(boundary.disk)
	var writes := boundary.writes.size()
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh(), "An identical room GET still reports successful verification")
	_check(boundary.writes.size() == writes and Canonical.digest(boundary.disk) == state_hash, "Identical room GET does not write or alter any durable state")
	boundary.fail_save = true
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes, "A verified unchanged read requires no writable save generation")
	boundary.fail_save = false
	var live: RefCounted = coordinator.create_live_simulation()
	_check(live != null, "Actual live producer is available before a read")
	live.step({"move_x": 1.0})
	_check(coordinator.save_live_draft(live), "An actual rehearsal tick is durably saved")
	state_hash = Canonical.digest(boundary.disk)
	writes = boundary.writes.size()
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes and Canonical.digest(boundary.disk) == state_hash, "Same-context read leaves the saved live draft unchanged")
	live.step({"move_x": 1.0})
	_check(coordinator.save_live_draft(live), "Unchanged read does not retire the registered live producer")
	boundary.responses.append(_error(503, "service_unavailable"))
	_check(not await coordinator.refresh() and not coordinator.last_error.is_empty(), "Transient read error is visible")
	writes = boundary.writes.size()
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh() and coordinator.last_error.is_empty() and boundary.writes.size() == writes, "Successful unchanged read clears the error without a write")

func _pending_receipt() -> void:
	var boundary := Boundary.new()
	var coordinator = await _open(boundary)
	_check(coordinator.save_draft(fixtures["relay-a"]), "Valid source draft exists before uncertain submission")
	_check(not await coordinator.commit(fixtures["relay-a"]), "Actual submission without acknowledgement remains pending")
	var sent: Dictionary = boundary.requests.back().duplicate(true)
	var pending: Dictionary = coordinator.pending()
	var old_room: Dictionary = coordinator.snapshot()
	var state_hash := Canonical.digest(boundary.disk)
	var writes := boundary.writes.size()
	boundary.responses.append(_ok(old_room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes, "Identical pre-acceptance GET does not write")
	_check(Canonical.same(coordinator.pending(), pending) and Canonical.digest(boundary.disk) == state_hash, "An unchanged room cannot acknowledge or alter an uncertain request")
	var accepted_room := _snapshot(HOST, 0, true, 2)
	boundary.responses.append(_ok(accepted_room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes + 1, "A genuinely newer verified snapshot is persisted")
	_check(Canonical.same(coordinator.pending(), pending) and coordinator.last_receipt().is_empty(), "Newer room progress alone still does not replace the exact receipt")
	state_hash = Canonical.digest(boundary.disk)
	writes = boundary.writes.size()
	boundary.responses.append(_ok(accepted_room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes and Canonical.digest(boundary.disk) == state_hash, "Repeated accepted snapshot leaves pending and held rehearsal bytes unchanged")
	boundary.responses.append(_ok(_receipt(sent, accepted_room)))
	_check(await coordinator.reconcile(), "Exact real receipt can acknowledge an already-current snapshot")
	_check(boundary.writes.size() == writes + 1 and coordinator.pending().is_empty() and coordinator.draft().is_empty(), "Receipt acceptance still persists and clears the exact pending operation")
	_check(coordinator.last_receipt().recording_hash == fixtures["relay-a"].recording_hash, "Receipt remains available to optional photo features")
	var reopened = _coordinator(boundary)
	_check(reopened.bind_room(ROOM) and reopened.pending().is_empty() and Canonical.same(reopened.last_receipt(), coordinator.last_receipt()), "Acknowledged state survives a fresh verified coordinator")

func _auth_and_validation() -> void:
	var boundary := Boundary.new()
	var coordinator = await _open(boundary)
	var room: Dictionary = coordinator.snapshot()
	boundary.responses.append(_error(401, "unauthorized"))
	_check(not await coordinator.refresh() and coordinator.snapshot().is_empty(), "Credential rejection hides the cached room")
	var writes := boundary.writes.size()
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh() and boundary.writes.size() == writes + 1, "Same room after fresh authenticated GET persists clearing auth-required")
	var reopened = _coordinator(boundary)
	_check(reopened.bind_room(ROOM) and Canonical.same(reopened.snapshot(), room), "Cleared authentication hold survives reload")
	var changed := room.duplicate(true)
	changed.updated_at = "2026-09-14T12:00:01Z"
	writes = boundary.writes.size()
	var state_hash := Canonical.digest(boundary.disk)
	boundary.responses.append(_ok(changed))
	_check(not await coordinator.refresh() and coordinator.last_code == "snapshot_conflict", "Modified same-revision metadata is still rejected")
	_check(boundary.writes.size() == writes and Canonical.digest(boundary.disk) == state_hash, "Conflicting snapshot never writes")
	changed = room.duplicate(true)
	changed.api_version = 99
	boundary.responses.append(_ok(changed))
	_check(not await coordinator.refresh() and not coordinator.my_turn(), "Unsupported reply still creates a transient remote hold")
	boundary.responses.append(_ok(room))
	_check(await coordinator.refresh() and coordinator.my_turn() and boundary.writes.size() == writes, "Fully verified identical room releases remote hold without rewriting state")
